### ISSUE TITLE
Monitor

### ISSUE THREAD

**Issue by audrey-b** [poissonconsulting/sims#17]
By default, shouldn't Y be monitored and not beta and epsilon since it is data (stochastic that is never reused on the right hand side)?

 sims_simulate("Y = beta + epsilon
               beta ~ dnorm(0,1)
               epsilon ~ dnorm(0,1)", nsim=1)
$beta
[1] -0.8499353

$epsilon
[1] -0.9987357

an nlists object of an nlist object with 2 natomic elements

**Comment by audrey-b** [comment]
sims_simulate("Y = beta + epsilon
               beta ~ dnorm(0,1)
               epsilon ~ dnorm(0,1)", nsim=1, latent=TRUE)
Error: jags code must include at least one latent stochastic variable node.

Should this output beta and epsilon?

**Comment by audrey-b** [comment]
= can still produce stochastic nodes if at least one of the things on the right hand side is stochastic. This might be hard to check because in e.g. the example below everything is stochastic, but you'd need a loop to identify all the stochastic nodes I think
a=b
b=c
c=d
d ~ dnorm(0,1)

**Comment by joethorley** [comment]
Now handles = same as <-

```sims_simulate("Y = beta + epsilon
beta ~ dnorm(0,1)
epsilon ~ dnorm(0,1)", nsim=1, latent=TRUE)```

```$beta
[1] -0.3409144

$epsilon
[1] 0.6874541

an nlists object of an nlist object with 2 natomic elements```

**Comment by joethorley** [comment]
It is true that = or <- can produce deterministic nodes that vary due to upstream stochastic nodes. However this applies to almost all deterministic nodes (otherwise there is no point in having them included in the model) ie there is no point trying to track them back to see if they vary or not. If you prefer we can set stochastic = NA by default in which case it will monitor stochastic and deterministic nodes - however in my somewhat limited experience nodes that I observe are generally stochastic.

**Comment by audrey-b** [comment]
That makes sense. Let's leave it as is.
