### ISSUE TITLE
Simulate missing datasets using replicable seed

### ISSUE THREAD

**Issue by audrey-b** [poissonconsulting/sims#19]
If a few datasets were deleted by mistake or those simulations failed for some reason, it would be nice to have a function that could resimulate those datasets using the same seed that was meant originally, without having to resimulate all the datasets.

Maybe that should be a new function called something like sims_restore or maybe there is a way to integrate it with the functions that already exist. For example, sims_simulate could have a retry=integer argument for how many times to retry when a simulations fails. And sims_check could have a retry argument as well, which would allow to resimulate datasets that disappeared for some reason

**Comment by joethorley** [comment]
sims determines the seed based on the provided seed and the iterations number so this is in principle relatively straightforward. I like the idea of sims_restore() dealing with deleted datasets. However I don't think we need the retry argument in sims_simulate() because we only doing one iteration and not trying to get convergence. Are you envisaging a case where a parameter is not provided by the user and the prior includes impossible values for downstream nodes?

**Comment by joethorley** [comment]
@audrey-b - Can you provide an example of a simulation that fails - we could update the seed for such failures but this is starting to get complicated and it might make sense to return an error and instruct the user to robustify their code.

Trying to recover when files have been deleted is doable but potentially dangerous as such a situation may indicate other problems such as changed files. In this case I think the best thing is the current behaviour which is to issue an informative error and to require the user to call sims_simulate() to regenerate all the files.

**Comment by joethorley** [comment]
@audrey-b Can I close this?
